services:
  - type: web
    name: clase_5_service
    runtime: python
    plan: free  # o 'starter' para $7/mes
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
    #healthCheckPath: /health
